name: Deploy NestJS App to VPS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select deployment environment"
        required: true
        default: "DEV"
        type: choice
        options:
          - DEV
          - PROD

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      # 1. Checkout code repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # 3. Install dependencies
      - name: Install Dependencies
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}  # Add DATABASE_URL from secrets
        run: npm install

      # 4. Run Prisma migration
      - name: Run Prisma Migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}  # Add DATABASE_URL from secrets
        run: npx prisma migrate deploy

      # 5. Build the application
      - name: Build Application
        run: npm run build

      # 6. Deploy to VPS
      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.VPS_HOST }}
          USERNAME: ${{ secrets.VPS_USERNAME }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
          rsync -avz --exclude=node_modules --exclude=.git ./ $USERNAME@$HOST:/var/www/contact-management-nestjs/backend
          
          # Create .env file on the VPS with the DATABASE_URL
          ssh $USERNAME@$HOST "grep -qxF 'DATABASE_URL=${{ secrets.DATABASE_URL }}' /var/www/contact-management-nestjs/backend/.env || echo 'DATABASE_URL=${{ secrets.DATABASE_URL }}' >> /var/www/contact-management-nestjs/backend/.env"
          ssh $USERNAME@$HOST "grep -qxF 'DATABASE=${{ secrets.DATABASE }}' /var/www/contact-management-nestjs/backend/.env || echo 'DATABASE=${{ secrets.DATABASE }}' >> /var/www/contact-management-nestjs/backend/.env"
          ssh $USERNAME@$HOST "grep -qxF 'PORT=${{ secrets.PORT }}' /var/www/contact-management-nestjs/backend/.env || echo 'PORT=${{ secrets.PORT }}' >> /var/www/contact-management-nestjs/backend/.env"

      # 7. Restart application using PM2
      - name: Restart Application
        env:
          HOST: ${{ secrets.VPS_HOST }}
          USERNAME: ${{ secrets.VPS_USERNAME }}
        run: |
          ssh $USERNAME@$HOST "
            cd /var/www/contact-management-nestjs/backend &&
            npm install --omit=dev &&
            pm2 delete contact-management-nestjs-backend || true &&
            pm2 start dist/main.js --name contact-management-nestjs-backend
          "
